name: Tea

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v27
      with: 
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build tea
      run: nix develop --build

    - name: Archive filesystem binary
      uses: actions/upload-artifact@v4
      with:
        name: filesystem
        path: ./filesystem/filesystem

    - name: Archive server binary
      uses: actions/upload-artifact@v4
      with:
        name: server
        path: ./server/server

  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v27
      with: 
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check formatting
      run: nix develop --command bash -c "make check-format"

  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v27
      with: 
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run unit tests
      run: nix develop --command bash -c "make unit-run"

  acceptance:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v27
      with: 
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare environment
      run: mkdir -p project-dir mount-dir

    - name: Build tea
      run: nix develop --build

    - name: Run server
      run: nix develop --command bash -c "sudo make server-run" &

    - name: Run filesystem
      run: nix develop --command bash -c "sudo ./filesystem/filesystem -f -h=127.0.0.1 mount-dir" &

    - name: Check filesystem is mounted
      run: findmnt mount-dir

    - name: Build tests
      run: nix develop --command bash -c "make acceptance"
    
    - name: Run tests
      run: nix develop --command bash -c "sudo ./tests/acceptance-runner"
