name: Tea

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v27
      with: 
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build tea
      run: nix develop --build

    - name: Archive filesystem binary
      uses: actions/upload-artifact@v4
      with:
        name: filesystem
        path: ./filesystem/filesystem

    - name: Archive server binary
      uses: actions/upload-artifact@v4
      with:
        name: server
        path: ./server/server
